#!/bin/sh

if [ ! -r "$HOME/dbus/Xdbus_geeknote_enabled" ]; then
	touch $HOME/.dbus/Xdbus_geeknote_enabled
	touch $HOME/.dbus/Xdbus
	chmod 600 $HOME/.dbus/Xdbus
	env | grep DBUS_SESSION_BUS_ADDRESS > $HOME/.dbus/Xdbus
	echo 'export DBUS_SESSION_BUS_ADDRESS' >> $HOME/.dbus/Xdbus
fi

if [ -r "$HOME/.dbus/Xdbus" ]; then
  . "$HOME/.dbus/Xdbus"
fi

export DISPLAY=:0.0
export XAUTHORITY=/home/timw/.Xauthority
sudo -u timw geeknote find --tags popup \
    | sed -e '1,2d' \
    | awk '{$1 = $2 = $3 = ""; print $0}' \
    | while read output; do notify-send --expire-time=100000 --icon=appointment-missed  "Evernote Reminder" "$output"; done 
